services:
  app:
    image: antonk92/node-express-app:latest
    container_name: node-express-app
    ports:
      - "8080:8080"
    restart: unless-stopped
  
  watchtower:
    image: containrrr/watchtower:1.5.3
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.44
    command: --interval 30
    restart: unless-stopped
    labels:
      - "com.containrrr.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"