services:
  app:
    image: antonk92/node-express-app:latest
    container_name: node-express-app
    ports:
      - "8080:8080"
    restart: unless-stopped
  
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json:ro
    environment:
      - DOCKER_API_VERSION=1.44
    command: --interval 30 --label-enable
    restart: unless-stopped
    labels:
      - "com.containrrr.watchtower.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"